### PR TITLE
Dec 2018 update

### PR DESCRIPTION
**Pull request by sdavis3**

### CODE REVIEW

**Comment by nyuen** [comment]
Hi, I've reviewed the latest version,

Just a quick note, I don't think it makes sense to ask to do a pull on the osticket project to enter enter in clear the credentials of the database as this is a bad practice even though this is just a workshop.

One of the step for the workshop is to copy the connection string to the app settings and I don't think this is then used in the code, I would instead add a step to pull the connection string from the environment variables passed by the App Service or even better perhaps introduce keyvault (perhaps out of scope of the workshop)

I would be valuable to add a gate on the pipeline to then auto swap to production

**Comment by nyuen** [comment]
@dmckinstry Agreeing on the change, we need to emphasis that this is CI/CD with Jenkins and Azure Web apps so let's simply call it "Azure WebApps CI/CD with Jenkins"

- Let's remove the VM, and just validate the list of pre-requisites on the user's laptop
- Let's remove the section where we require the user to commit there credentials on the PHP script, this is a no go for me and we should replace that with AppSettings or a KeyVault
- Update the workshop abstract to something like : 
"In this workshop, you will look at options for migrating an online health food supplier from a hosted environment to Azure and implementing a CI/CD pipeline on Jenkins. You will investigate running a PHP+MySql workload using Platform-as-a-Service (PaaS) services that can leverage your existing knowledge of Jenkins."
-Review every use of "Open Source (OSS)", and simply replace that with PHP/MySQL. Using PHP and MySql doesn't imply that this is related to an OpenSource project, it's "just" a website at the end of the day.

**Comment by DawnmarieDesJardins** [comment]
@sdavis3 @mwasham 
Hello!  We're received lead sign-off on this update.  Please finalize the documents, close any open issues and send for editing.  Let me know when it's ready for me to QC/merge.  Thanks, Dawnmarie

**Comment by sdavis3** [comment]
To the best of my knowledge this update has been completed and is ready for merge. The issues will close automatically when the pull request is merged.

**Pull request merged**
